/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonParser;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Collection;
public class App {

    Gson gson = new Gson();

    File file = new File("app/src/main/resources/recent-quotes.json");
    FileReader fileReader = new FileReader(file);
    Type collectionType = new TypeToken<Collection<Quotes>>(){}.getType();
    ArrayList<Quotes> quotesArrayList = gson.fromJson(fileReader, collectionType);
    int index =  new Random().nextInt(quotesArrayList.size());

    System.out.println(quotesArrayList.get(int).getAuthor());
    System.out.println(quotesArrayList.get(int).getText();

    public App() throws FileNotFoundException {
    });

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
